CREATE DATABASE microservicio_cliente;
CREATE DATABASE microservicio_evaluacion_credito;
CREATE DATABASE microservicio_seguimiento_solicitud;
CREATE DATABASE microservicio_simulacion_credito;
CREATE DATABASE microservicio_solicitud_credito;
CREATE DATABASE microservicio_tipo_prestamo;