server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: bussiness-logic-service
 
 
eureka:
  instance:
    preferIpAddress: true
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true