server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: solicitud-credito-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservicio-solicitud-credito
    username: victorvaraspro
    password: hola2020
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.connection.autocommit: false
eureka:
  instance:
    preferIpAddress: true
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true