server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: solicitud-credito-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/microservicio_solicitud_credito
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate.connection.autocommit: false
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://eureka-deployment:8761/eureka
    fetch-registry: true
    register-with-eureka: true