apiVersion: apps/v1
kind: Deployment
metadata:
  name: bussiness-logic-deployment
  labels:
    app: bussiness-logic-deployment
spec:
  selector:
    matchLabels:
      app: bussiness-logic-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: bussiness-logic-deployment
    spec:
      containers:
        - name: bussiness-logic
          image: victorvaraspro/business_logic:latest      
          env:
            - name: SERVER_PORT
              value: "0"