apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-deployment
  labels:
    app: config-deployment
spec:
  selector:
    matchLabels:
      app: config-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: config-deployment
    spec:
      containers:
        - name: config-deployment
          image: victorvaraspro/config-service:latest
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: config-deployment-service
  labels:
    app: config-deployment-service
spec:
  selector:
    app: config-deployment
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
