apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
        - name: eureka-deployment
          image: victorvaraspro/eureka-service:latest  # Cambia esta imagen por la correcta
          ports:
            - containerPort: 8761  # El puerto estándar de Eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  selector:
    app: eureka-deployment
  ports:
    - protocol: TCP
      port: 8761  # El puerto en el que estará accesible Eureka
      targetPort: 8761
  type: LoadBalancer
