apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluacion-credito-deployment
  labels:
    app: evaluacion-credito-deployment
spec:
  selector:
    matchLabels:
      app: evaluacion-credito-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: evaluacion-credito-deployment
    spec:
      containers:
        - name: evaluacion-credito
          image: victorvaraspro/evaluacion-credito-services:latest        
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_EVALUACION-CREDITO
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_EVALUACION-CREDITO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_EVALUACION-CREDITO
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_EVALUACION-CREDITO