apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploymen
  labels:
    app: gateway-deployment
spec:
  selector:
    matchLabels:
      app: gateway-deployment

  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-deployment
  
    spec:
      containers:
        - name: gateway-deployment
  
          image: victorvaraspro/geteway-service:latest 
          ports:
            - containerPort: 8080  
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-deploymen
  labels:
    app: gateway-deployment
spec:
  selector:
    app: gateway-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
