apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USER_TIPO-PRESTAMO: dmljdG9ydmFyYXNwcm8=
  DB_PASSWORD_TIPO-PRESTAMO: aG9sYTIwMjA=

  DB_USER_SEGUIMIENTO-SOLICITUD: dmljdG9ydmFyYXNwcm8=
  DB_PASSWORD_SEGUIMIENTO-SOLICITUD: aG9sYTIwMjA=