apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulacion-credito-deployment
  labels:
    app: simulacion-credito-deployment
spec:
  selector:
    matchLabels:
      app: simulacion-credito-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: simulacion-credito-deployment
    spec:
      containers:
        - name: simulacion-credito
          image: victorvaraspro/simulacion-credito-services:latest        
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_SIMULACION-CREDITO
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_SIMULACION-CREDITO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_SIMULACION-CREDITO
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_SIMULACION-CREDITO