apiVersion: apps/v1
kind: Deployment
metadata:
  name: solicitud-credito-deployment
  labels:
    app: solicitud-credito-deployment
spec:
  selector:
    matchLabels:
      app: solicitud-credito-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: solicitud-credito-deployment
    spec:
      containers:
        - name: solicitud-credito
          image: victorvaraspro/solicitud-credito-services:latest        
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_SOLICITUD-CREDITO
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_SOLICITUD-CREDITO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_SOLICITUD-CREDITO
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_SOLICITUD-CREDITO