apiVersion: apps/v1
kind: Deployment
metadata:
  name: tipo-prestamo-deployment
  labels:
    app: tipo-prestamo-deployment
spec:
  selector:
    matchLabels:
      app: tipo-prestamo-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: tipo-prestamo-deployment
    spec:
      containers:
        - name: tipo-prestamo
          image: victorvaraspro/tipo-prestamo-services:latest        
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_TIPO-PRESTAMO
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_TIPO-PRESTAMO
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_TIPO-PRESTAMO
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_TIPO-PRESTAMO