server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorvaras/Tingeso-microservicios.git
          default-label: main
          search-paths: config-data
